map/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from map.views import MapView
from map.api import router

urlpatterns = [
    url(r'^$', MapView.as_view(), name="index"),
    url(r'^api/', include(router.urls)),
]

ucm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

admin.site.site_header =  "UnicycleMap.com administration"

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url('^', include('django.contrib.auth.urls')),
    url(r'^', include("map.urls", app_name="map", namespace="map")),
]

if settings.DEBUG:
    urlpatterns += [ 
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]

map/models.py
from __future__ import unicode_literals

from django.contrib.gis.db import models
from django.conf import settings
from django_countries.fields import CountryField
from django.utils.translation import ugettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.
class Event(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, help_text=_("Tho user who is responsible for the event"))
    logo = models.ImageField(null=True, blank=True, upload_to="event_logos", help_text=_("A logo to display on the event page"))
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True, help_text=_("Short description of the event"))
    begin_date = models.DateTimeField()
    end_date = models.DateTimeField(blank=True, null=True, help_text=_("Can be left empty"))

    # location specific fields
    geopos = models.PointField(verbose_name=_("Geo Location"))
    address = models.TextField(blank=True)
    zipcode = models.CharField(max_length=15, blank=True, verbose_name=_("ZIP Code"))
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100, blank=True)
    country = CountryField()

    class Meta:
        ordering = ("-begin_date", "title")

    def __unicode__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    display_name = models.CharField(max_length=100)
    avatar = models.ImageField(null=True, blank=True, upload_to="user_avatars", help_text=_("Uploaded a photo that is displayed as an avatar next to your username"))
    description = models.TextField(blank=True, help_text=_("Short description of you and your unicycling activities"))
    phone = PhoneNumberField(blank=True)
    show_email = models.BooleanField(default=False, help_text=_("Show your email to other registered users"))

    # location specific fields
    geopos = models.PointField(verbose_name=_("Geo Location"), blank=True, null=True)
    city = models.CharField(max_length=100, blank=True)
    state = models.CharField(max_length=100, blank=True)
    country = CountryField(blank=True, null=True)


    def __unicode__(self):
        return self.display_name

map/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from map.models import Event, UserProfile
from django.contrib.gis.db.models.functions import Distance

class MapView(TemplateView):
    template_name = "map/index.html"

    def get_context_data(self, **kwargs):
        context = super(MapView, self).get_context_data()
        events = Event.objects.all()
        
        if self.request.user.is_authenticated():
            try:
                pos = self.request.user.userprofile.geopos
            except UserProfile.DoesNotExist:
                pass
            else:
                events = events.annotate(distance=Distance("geopos", pos))

        context["events"] = events
        return context

# Create your views here.

map/templates/map/index.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% block title %}{% trans "Welcome" %}{% endblock %}
{% block content %}
<div id="container" ng-controller="MapController as mapctrl">
    <div id="map-sidebar" class="sidebar">
        <div class="sidebar-tabs">
            <ul role="tablist">
                <li class="active"><a href="#home" role="tab"><i class="fa fa-bars"></i></a></li>
                <li uib-tooltip="{% trans "Edit profile" %}" tooltip-placement="right"><a href="#pencil" role="tab"><i class="fa fa-pencil"></i></a></li>
                <li><a href="#envelope" role="tab"><i class="fa fa-envelope"></i></a></li>
            </ul>
            <ul role="tablist">
                <li><a href="#cogs" role="tab"><i class="fa fa-cogs"></i></a></li>
            </ul>
        </div>
        <div class="sidebar-content">
            <div class="sidebar-pane active" id="home">
                <h1 class="sidebar-header">
                    Welcome
                    <span class="sidebar-close"><i class="fa fa-caret-left"></i></span>
                </h1>
                <p>
                    <p class="well">
                        {% blocktrans %}
                            Addicted to unicycling? Great! Then get in touch with others: Simply <a href="">sign up</a> with your email address or directly <a href="">login</a> via Facebook and put your marker on the map.
                        {% endblocktrans %} 
                    </p>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <button class="pull-right btn btn-xs btn-primary"><i class="fa fa-arrow-right"></i> more</button>
                            <h3 class="panel-title"><i class="fa fa-calendar"></i> {% trans "What's up next?" %}</h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-hover table-condensed">
                                    <thead>
                                        <tr>
                                            <th class="col-xs-8">Event</th>
                                            <th class="col-xs-4">Date</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for event in events|slice:"4" %}
                                        <tr>
                                            <td ng-mouseenter="mapctrl.focusEvent({{event.id}})">
                                                <a href="" ng-click="mapctrl.focusEvent({{event.id}})"><strong>{{event.title}}</strong></a><br> <small><i class="fa fa-map-marker"></i> {{event.city}}, {% if event.state %}{{event.state}}, {% endif %} {{event.country}} {% if event.distance %}<span class="text-info">{{event.distance.km|floatformat:"1"}} km</span>{% endif %}</small>
                                            </td>
                                            <td>
                                                {{event.begin_date|date:"SHORT_DATE_FORMAT"}} <br><i class="fa fa-clock-o"></i> {{event.begin_date|time:"TIME_FORMAT"}}
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                        
                                </table>
                            </div>
                        </div><!-- /.panel-body -->
                    </div><!-- /.panel -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <button class="pull-right btn btn-xs btn-primary"><i class="fa fa-arrow-right"></i> more</button>
                            <h3 class="panel-title"><i class="fa fa-image"></i> New Images in the Community</h3>
                        </div>
                        <div class="panel-body">
                            <div class="img-responsive"><img src="http://adventureweek.org/wp-content/uploads/2016/02/Uni2.jpg"></div>
                        </div>
                    </div>
                </p>
            </div> <!-- /.sidebar-pane -->
        </div><!-- /.sidebar-content -->
    </div>
        <leaflet id="ucmap" class="sidebar-map" layers="mapctrl.layers" controls="mapctrl.controls" center="mapctrl.center" markers="mapctrl.markers"></leaflet>
</div>
{% endblock %}

ucm/templates/base.html
{% load pipeline %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en" ng-app="ucm">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>UnicycleMap.com :: {% block title %}{% endblock %}</title>

    {% stylesheet "base" %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#ucm-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">{% trans "Toggle navigation" %}</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">UnicycleMap.com</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="ucm-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url "map:index" %}"><i class="fa fa-map"></i> {% trans "Map" %}<span class="sr-only">(current)</span></a></li>
            <li><a href="#"><i class="fa fa-users"></i> {% trans "Users" %}</a></li>
            <li><a href="#"><i class="fa fa-calendar"></i> {% trans "Events" %}</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <div class="input-group">
              <input type="search" class="form-control" placeholder="{% trans "Search users or events..." %}">
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                </span>
            </div>
          </form>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i> {{user}}<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">{% trans "My Profile" %}</a></li>
                    <li><a href="{% url "password_change" %}">{% trans "Change Password" %}</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url "logout" %}"><i class="fa fa-sign-out"></i> {% trans "Log Out" %}</a></li>
                  </ul>
                </li>
            {% else %}
                <li><a href="{% url "login" %}"><i class="fa fa-sign-in"></i> {% trans "Log In" %}</a></li>
            {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
 
    {% block content %}{% endblock %}
    {% javascript "base" %}
    {% block scripts %}
    {% endblock %}
  </body>
</html> 